image: docker:24.0.5
services:
  - name: registry.hub.docker.com/library/docker:24.0.5-dind
    alias: docker

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Build"
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker images
    - docker save  $CI_REGISTRY_IMAGE > $CI_REGISTRY_IMAGE.tar

test-job:
  stage: test
  script:
    - echo "Tests..."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."