image: docker:24.0.5
services:
  - name: registry.hub.docker.com/library/docker:24.0.5-dind
    alias: docker

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Build"
    - docker build -t my-first-image .

test-job:
  stage: test
  script: echo "Tests..."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."