image: docker:24.0.5
services:
  - name: registry.hub.docker.com/library/docker:24.0.5-dind
    alias: docker

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Build"
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker images
    - docker save  $CI_REGISTRY_IMAGE > $CI_REGISTRY_IMAGE.tar
  artifacts:
    paths:
        - $CI_REGISTRY_IMAGE.tar

test-job:
  stage: test
  script:
    - echo "Tests..."

deploy-job:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SERVER_PRIVATE_KEY" | base64 -d)
  script:
    - echo "Deploying application..."
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_URL "

# jobDeploy:
#   stage: deploy
#   script:
#     - scp -o StrictHostKeyChecking=no -r build $SERVER_USER@$SERVER_URL:workspace/smoooth-esg-portal
#     - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_URL "
#       docker compose pull &&
#       docker compose up -d --build
#       "